// ============================================================================
// Lightning Receiver - DDC Complex Mixer with sample-synchronous NCO
// File: ddc_mixer.v
// ----------------------------------------------------------------------------
// Downconverts the LR IQ stream by a complex NCO tone:
//   y = x * e^{-j*phi[n]},   phi[n+1] = phi[n] + PINC   (one step per sample)
// so a positive tuning word moves RF energy at (LO + f) to 0 Hz.
//
// The NCO advances exactly once per *accepted input sample*.  The former
// design sampled a DDS that free-ran on the 225 MHz fabric clock, so the
// mixing phase followed the sample *arrival* time.  AD9361 samples reach the
// fabric asynchronously with +/-1 clock (and FIFO burst) jitter, which turned
// into phase noise proportional to the tuning offset (~0.3 rad at 10 MHz).
//
// Phase-to-amplitude: 12-bit phase, quarter-wave ROM lr_nco_sine_rom.v
// (1024 x Q1.15, generated by tools/gen_dsp_tables.py), ~72 dB SFDR.  Output gain is x8 (>>> 12):
// AD9361 12-bit samples (|x| <= 2048*sqrt(2)) stay below 23170, keeping three
// more bits of precision ahead of the 320x CIC.  Results saturate to 16 bits.
// ============================================================================
`timescale 1ns/1ps
`include "lr_defines.vh"

module ddc_mixer (
    input  wire              clk,
    input  wire              rst_n,
    // NCO tuning word per sample (from nco_phase_control); always accepted
    (* X_INTERFACE_IGNORE = "true" *) input wire [31:0] pinc_tdata,
    (* X_INTERFACE_IGNORE = "true" *) input wire pinc_tvalid,
    // stream in
    input  wire [`LR_TDATA_W-1:0] s_tdata,
    input  wire [`LR_TUSER_W-1:0] s_tuser,
    input  wire              s_tvalid,
    output wire              s_tready,
    input  wire              s_tlast,
    // stream out
    output reg  [`LR_TDATA_W-1:0] m_tdata,
    output reg  [`LR_TUSER_W-1:0] m_tuser,
    output reg               m_tvalid,
    input  wire              m_tready,
    output reg               m_tlast
);

    reg [31:0] pinc;
    reg [31:0] phase_acc;

    // Elastic pipeline: every stage advances on pipe_ce.
    wire pipe_ce = !m_tvalid || m_tready;
    wire accept  = s_tvalid && s_tready;
    assign s_tready = pipe_ce;

    wire [1:0] quad = phase_acc[31:30];
    wire [9:0] idx  = phase_acc[29:20];
    wire [9:0] addr_s = quad[0] ? ~idx : idx;
    wire [9:0] addr_c = quad[0] ? idx : ~idx;

    // Stage a: input sample + quarter-wave ROM read (registered, no reset);
    // the ROM output lines up with the stage-a sample registers.
    wire [15:0] rom_s_a, rom_c_a;
    lr_nco_sine_rom u_rom (
        .clk(clk), .ce(pipe_ce),
        .addr_a(addr_s), .addr_b(addr_c),
        .dout_a(rom_s_a), .dout_b(rom_c_a));

    reg signed [15:0] xi_a, xq_a, xi_b, xq_b;
    reg               neg_s_a, neg_c_a;
    reg signed [16:0] s_b, c_b;            // +/-32767 after sign
    reg signed [32:0] p1, p2, p3, p4;      // xi*c, xq*s, xi*s, xq*c
    reg signed [33:0] yi, yq;
    reg [`LR_TUSER_W-1:0] user_a, user_b, user_c, user_d;
    reg last_a, last_b, last_c, last_d;
    reg valid_a, valid_b, valid_c, valid_d;

    function [15:0] sat16;
        input signed [33:0] v;
        begin
            if (v > 34'sd32767)
                sat16 = 16'h7FFF;
            else if (v < -34'sd32768)
                sat16 = 16'h8000;
            else
                sat16 = v[15:0];
        end
    endfunction

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            pinc <= 32'd0;
            phase_acc <= 32'd0;
            xi_a <= 16'sd0; xq_a <= 16'sd0; xi_b <= 16'sd0; xq_b <= 16'sd0;
            neg_s_a <= 1'b0; neg_c_a <= 1'b0;
            s_b <= 17'sd0; c_b <= 17'sd0;
            p1 <= 33'sd0; p2 <= 33'sd0; p3 <= 33'sd0; p4 <= 33'sd0;
            yi <= 34'sd0; yq <= 34'sd0;
            user_a <= {`LR_TUSER_W{1'b0}}; user_b <= {`LR_TUSER_W{1'b0}};
            user_c <= {`LR_TUSER_W{1'b0}}; user_d <= {`LR_TUSER_W{1'b0}};
            last_a <= 1'b0; last_b <= 1'b0; last_c <= 1'b0; last_d <= 1'b0;
            valid_a <= 1'b0; valid_b <= 1'b0; valid_c <= 1'b0; valid_d <= 1'b0;
            m_tdata <= {`LR_TDATA_W{1'b0}};
            m_tuser <= {`LR_TUSER_W{1'b0}};
            m_tvalid <= 1'b0;
            m_tlast <= 1'b0;
        end else begin
            if (pinc_tvalid)
                pinc <= pinc_tdata;

            if (pipe_ce) begin
                // Stage e: registered, saturated stream output.
                m_tvalid <= valid_d;
                if (valid_d) begin
                    m_tdata[31:16] <= sat16(yi >>> 12);
                    m_tdata[15:0]  <= sat16(yq >>> 12);
                    m_tuser <= user_d;
                    m_tlast <= last_d;
                end

                // Stage d: complex sum.
                valid_d <= valid_c;
                if (valid_c) begin
                    yi <= p1 + p2;          // xi*cos + xq*sin
                    yq <= p4 - p3;          // xq*cos - xi*sin
                    user_d <= user_c;
                    last_d <= last_c;
                end

                // Stage c: four DSP multipliers.
                valid_c <= valid_b;
                if (valid_b) begin
                    p1 <= xi_b * c_b;
                    p2 <= xq_b * s_b;
                    p3 <= xi_b * s_b;
                    p4 <= xq_b * c_b;
                    user_c <= user_b;
                    last_c <= last_b;
                end

                // Stage b: apply quadrant sign to the ROM outputs.
                valid_b <= valid_a;
                if (valid_a) begin
                    s_b <= neg_s_a ? -$signed({1'b0, rom_s_a})
                                   :  $signed({1'b0, rom_s_a});
                    c_b <= neg_c_a ? -$signed({1'b0, rom_c_a})
                                   :  $signed({1'b0, rom_c_a});
                    xi_b <= xi_a;
                    xq_b <= xq_a;
                    user_b <= user_a;
                    last_b <= last_a;
                end

                // Stage a: accept one sample, read sin/cos for its phase and
                // advance the NCO by exactly one sample period.
                valid_a <= accept;
                if (accept) begin
                    xi_a <= s_tdata[31:16];
                    xq_a <= s_tdata[15:0];
                    neg_s_a <= quad[1];
                    neg_c_a <= quad[1] ^ quad[0];
                    user_a <= s_tuser;
                    last_a <= s_tlast;
                    phase_acc <= phase_acc + pinc;
                end
            end
        end
    end

endmodule
