// ============================================================================
// Lightning Receiver - audio decimation FIR coefficient ROM
// File: lr_audio_fir_rom.v
// ----------------------------------------------------------------------------
// GENERATED by tools/gen_dsp_tables.py - do not edit by hand.
// 191 taps, fs 192 kHz, pass 0-15 kHz, stop >= 19 kHz (~60 dB, removes the
// 19 kHz stereo pilot), Kaiser beta 5.65, Q1.17, sum = 2^17 (unity DC gain).
// Synchronous read with clock enable.
// ============================================================================
`timescale 1ns/1ps

module lr_audio_fir_rom (
    input  wire               clk,
    input  wire               ce,
    input  wire [7:0]         addr,
    output reg  signed [17:0] dout
);

    localparam integer TAPS = 191;

    function signed [17:0] coef;
        input [7:0] k;
        begin
            case (k)
            8'd0: coef = 18'sd5;
            8'd1: coef = 18'sd10;
            8'd2: coef = 18'sd12;
            8'd3: coef = 18'sd11;
            8'd4: coef = 18'sd6;
            8'd5: coef = -18'sd4;
            8'd6: coef = -18'sd15;
            8'd7: coef = -18'sd23;
            8'd8: coef = -18'sd26;
            8'd9: coef = -18'sd20;
            8'd10: coef = -18'sd5;
            8'd11: coef = 18'sd14;
            8'd12: coef = 18'sd33;
            8'd13: coef = 18'sd45;
            8'd14: coef = 18'sd44;
            8'd15: coef = 18'sd27;
            8'd16: coef = -18'sd2;
            8'd17: coef = -18'sd36;
            8'd18: coef = -18'sd63;
            8'd19: coef = -18'sd75;
            8'd20: coef = -18'sd63;
            8'd21: coef = -18'sd28;
            8'd22: coef = 18'sd22;
            8'd23: coef = 18'sd72;
            8'd24: coef = 18'sd107;
            8'd25: coef = 18'sd112;
            8'd26: coef = 18'sd80;
            8'd27: coef = 18'sd18;
            8'd28: coef = -18'sd60;
            8'd29: coef = -18'sd128;
            8'd30: coef = -18'sd165;
            8'd31: coef = -18'sd152;
            8'd32: coef = -18'sd88;
            8'd33: coef = 18'sd13;
            8'd34: coef = 18'sd123;
            8'd35: coef = 18'sd207;
            8'd36: coef = 18'sd234;
            8'd37: coef = 18'sd189;
            8'd38: coef = 18'sd77;
            8'd39: coef = -18'sd73;
            8'd40: coef = -18'sd217;
            8'd41: coef = -18'sd309;
            8'd42: coef = -18'sd311;
            8'd43: coef = -18'sd214;
            8'd44: coef = -18'sd36;
            8'd45: coef = 18'sd173;
            8'd46: coef = 18'sd349;
            8'd47: coef = 18'sd433;
            8'd48: coef = 18'sd387;
            8'd49: coef = 18'sd212;
            8'd50: coef = -18'sd50;
            8'd51: coef = -18'sd324;
            8'd52: coef = -18'sd523;
            8'd53: coef = -18'sd577;
            8'd54: coef = -18'sd451;
            8'd55: coef = -18'sd168;
            8'd56: coef = 18'sd198;
            8'd57: coef = 18'sd539;
            8'd58: coef = 18'sd744;
            8'd59: coef = 18'sd732;
            8'd60: coef = 18'sd485;
            8'd61: coef = 18'sd57;
            8'd62: coef = -18'sd434;
            8'd63: coef = -18'sd838;
            8'd64: coef = -18'sd1017;
            8'd65: coef = -18'sd890;
            8'd66: coef = -18'sd465;
            8'd67: coef = 18'sd155;
            8'd68: coef = 18'sd794;
            8'd69: coef = 18'sd1250;
            8'd70: coef = 18'sd1357;
            8'd71: coef = 18'sd1041;
            8'd72: coef = 18'sd354;
            8'd73: coef = -18'sd530;
            8'd74: coef = -18'sd1353;
            8'd75: coef = -18'sd1844;
            8'd76: coef = -18'sd1803;
            8'd77: coef = -18'sd1174;
            8'd78: coef = -18'sd74;
            8'd79: coef = 18'sd1212;
            8'd80: coef = 18'sd2300;
            8'd81: coef = 18'sd2812;
            8'd82: coef = 18'sd2486;
            8'd83: coef = 18'sd1277;
            8'd84: coef = -18'sd597;
            8'd85: coef = -18'sd2673;
            8'd86: coef = -18'sd4334;
            8'd87: coef = -18'sd4946;
            8'd88: coef = -18'sd4017;
            8'd89: coef = -18'sd1343;
            8'd90: coef = 18'sd2918;
            8'd91: coef = 18'sd8236;
            8'd92: coef = 18'sd13802;
            8'd93: coef = 18'sd18685;
            8'd94: coef = 18'sd22021;
            8'd95: coef = 18'sd23208;
            8'd96: coef = 18'sd22021;
            8'd97: coef = 18'sd18685;
            8'd98: coef = 18'sd13802;
            8'd99: coef = 18'sd8236;
            8'd100: coef = 18'sd2918;
            8'd101: coef = -18'sd1343;
            8'd102: coef = -18'sd4017;
            8'd103: coef = -18'sd4946;
            8'd104: coef = -18'sd4334;
            8'd105: coef = -18'sd2673;
            8'd106: coef = -18'sd597;
            8'd107: coef = 18'sd1277;
            8'd108: coef = 18'sd2486;
            8'd109: coef = 18'sd2812;
            8'd110: coef = 18'sd2300;
            8'd111: coef = 18'sd1212;
            8'd112: coef = -18'sd74;
            8'd113: coef = -18'sd1174;
            8'd114: coef = -18'sd1803;
            8'd115: coef = -18'sd1844;
            8'd116: coef = -18'sd1353;
            8'd117: coef = -18'sd530;
            8'd118: coef = 18'sd354;
            8'd119: coef = 18'sd1041;
            8'd120: coef = 18'sd1357;
            8'd121: coef = 18'sd1250;
            8'd122: coef = 18'sd794;
            8'd123: coef = 18'sd155;
            8'd124: coef = -18'sd465;
            8'd125: coef = -18'sd890;
            8'd126: coef = -18'sd1017;
            8'd127: coef = -18'sd838;
            8'd128: coef = -18'sd434;
            8'd129: coef = 18'sd57;
            8'd130: coef = 18'sd485;
            8'd131: coef = 18'sd732;
            8'd132: coef = 18'sd744;
            8'd133: coef = 18'sd539;
            8'd134: coef = 18'sd198;
            8'd135: coef = -18'sd168;
            8'd136: coef = -18'sd451;
            8'd137: coef = -18'sd577;
            8'd138: coef = -18'sd523;
            8'd139: coef = -18'sd324;
            8'd140: coef = -18'sd50;
            8'd141: coef = 18'sd212;
            8'd142: coef = 18'sd387;
            8'd143: coef = 18'sd433;
            8'd144: coef = 18'sd349;
            8'd145: coef = 18'sd173;
            8'd146: coef = -18'sd36;
            8'd147: coef = -18'sd214;
            8'd148: coef = -18'sd311;
            8'd149: coef = -18'sd309;
            8'd150: coef = -18'sd217;
            8'd151: coef = -18'sd73;
            8'd152: coef = 18'sd77;
            8'd153: coef = 18'sd189;
            8'd154: coef = 18'sd234;
            8'd155: coef = 18'sd207;
            8'd156: coef = 18'sd123;
            8'd157: coef = 18'sd13;
            8'd158: coef = -18'sd88;
            8'd159: coef = -18'sd152;
            8'd160: coef = -18'sd165;
            8'd161: coef = -18'sd128;
            8'd162: coef = -18'sd60;
            8'd163: coef = 18'sd18;
            8'd164: coef = 18'sd80;
            8'd165: coef = 18'sd112;
            8'd166: coef = 18'sd107;
            8'd167: coef = 18'sd72;
            8'd168: coef = 18'sd22;
            8'd169: coef = -18'sd28;
            8'd170: coef = -18'sd63;
            8'd171: coef = -18'sd75;
            8'd172: coef = -18'sd63;
            8'd173: coef = -18'sd36;
            8'd174: coef = -18'sd2;
            8'd175: coef = 18'sd27;
            8'd176: coef = 18'sd44;
            8'd177: coef = 18'sd45;
            8'd178: coef = 18'sd33;
            8'd179: coef = 18'sd14;
            8'd180: coef = -18'sd5;
            8'd181: coef = -18'sd20;
            8'd182: coef = -18'sd26;
            8'd183: coef = -18'sd23;
            8'd184: coef = -18'sd15;
            8'd185: coef = -18'sd4;
            8'd186: coef = 18'sd6;
            8'd187: coef = 18'sd11;
            8'd188: coef = 18'sd12;
            8'd189: coef = 18'sd10;
            8'd190: coef = 18'sd5;
            default: coef = 18'sd0;
            endcase
        end
    endfunction

    always @(posedge clk) begin
        if (ce)
            dout <= coef(addr);
    end

endmodule
