"""Generate fixed DSP tables used by the LR RTL.

Outputs:
  rtl/dsp/lr_nco_sine_rom.v  - dual-read quarter-wave sine ROM module
                               (1024 x Q1.15, sampled at (k+0.5) for symmetry)
  stdout                     - CORDIC atan table (pi = 2^19) for fm_demod.v

The ROM is emitted as a self-contained module (case-statement ROM) instead
of an include/mem file: Vivado parses every .vh it is given as a standalone
source, and $readmemh paths differ between xsim and synthesis runs.

Run from anywhere:  python tools/gen_dsp_tables.py
"""
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QUARTER = 1024
AMP = 32767

entries = []
for k in range(QUARTER):
    v = round(AMP * math.sin(math.pi / 2 * (k + 0.5) / QUARTER))
    entries.append(f"            10'd{k}: qsin = 16'd{v};")

module = f"""// ============================================================================
// Lightning Receiver - NCO quarter-wave sine ROM (dual read port)
// File: lr_nco_sine_rom.v
// ----------------------------------------------------------------------------
// GENERATED by tools/gen_dsp_tables.py - do not edit by hand.
// rom[k] = round(32767 * sin(pi/2 * (k + 0.5) / 1024)), k = 0..1023.
// Sampling at bin centres makes the table symmetric under index inversion,
// so sin and cos for all four quadrants come from the same 1024 entries.
// Synchronous read with clock enable (maps to block ROM).
// ============================================================================
`timescale 1ns/1ps

module lr_nco_sine_rom (
    input  wire        clk,
    input  wire        ce,
    input  wire [9:0]  addr_a,
    input  wire [9:0]  addr_b,
    output reg  [15:0] dout_a,
    output reg  [15:0] dout_b
);

    function [15:0] qsin;
        input [9:0] k;
        begin
            case (k)
{chr(10).join(entries)}
            default: qsin = 16'd0;
            endcase
        end
    endfunction

    always @(posedge clk) begin
        if (ce) begin
            dout_a <= qsin(addr_a);
            dout_b <= qsin(addr_b);
        end
    end

endmodule
"""
out = ROOT / "rtl" / "dsp" / "lr_nco_sine_rom.v"
out.write_text(module, encoding="ascii")
print(f"wrote {out}")

# ---------------------------------------------------------------------------
# Audio anti-alias / decimation FIR for audio_pipeline.v (192 kHz -> 48 kHz)
#   191 taps, Kaiser beta 5.65, pass 15 kHz, stop >= 19 kHz (removes the
#   stereo pilot), Q1.17 coefficients with exact unity DC gain.
# ---------------------------------------------------------------------------
import numpy as np

FIR_FS, FIR_FP, FIR_FST, FIR_N = 192000.0, 15000.0, 19000.0, 191
fc = (FIR_FP + FIR_FST) / 2 / FIR_FS
nn = np.arange(FIR_N) - (FIR_N - 1) / 2
h = 2 * fc * np.sinc(2 * fc * nn) * np.kaiser(FIR_N, 5.65)
h /= h.sum()
q = np.round(h * (1 << 17)).astype(int)
q[(FIR_N - 1) // 2] += (1 << 17) - q.sum()
fir_entries = []
for k, v in enumerate(q):
    lit = f"18'sd{v}" if v >= 0 else f"-18'sd{-v}"
    fir_entries.append(f"            8'd{k}: coef = {lit};")

fir_module = f"""// ============================================================================
// Lightning Receiver - audio decimation FIR coefficient ROM
// File: lr_audio_fir_rom.v
// ----------------------------------------------------------------------------
// GENERATED by tools/gen_dsp_tables.py - do not edit by hand.
// {FIR_N} taps, fs 192 kHz, pass 0-15 kHz, stop >= 19 kHz (~60 dB, removes the
// 19 kHz stereo pilot), Kaiser beta 5.65, Q1.17, sum = 2^17 (unity DC gain).
// Synchronous read with clock enable.
// ============================================================================
`timescale 1ns/1ps

module lr_audio_fir_rom (
    input  wire               clk,
    input  wire               ce,
    input  wire [7:0]         addr,
    output reg  signed [17:0] dout
);

    localparam integer TAPS = {FIR_N};

    function signed [17:0] coef;
        input [7:0] k;
        begin
            case (k)
{chr(10).join(fir_entries)}
            default: coef = 18'sd0;
            endcase
        end
    endfunction

    always @(posedge clk) begin
        if (ce)
            dout <= coef(addr);
    end

endmodule
"""
out = ROOT / "rtl" / "dsp" / "lr_audio_fir_rom.v"
out.write_text(fir_module, encoding="ascii")
print(f"wrote {out} ({FIR_N} taps, max coef {q.max()})")

print("CORDIC atan table (angle units: pi = 2^19):")
for i in range(20):
    a = round(math.atan(2.0 ** -i) / math.pi * (1 << 19))
    print(f"  {i:2d}: 20'd{a}")
